global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: test
      password: test
    static_configs:
      - targets: ['app:8080']